### ISSUE TITLE
Feature request: draw an arrow

### ISSUE THREAD

**Issue by lebe-dev** [kakoc/birdy#2]
It would be great to draw arrows with medium size lines.

May be with color option: red, green, green (this part for discussion).

**Comment by kakoc** [comment]
Added filled/not filled arrows.  

![image](https://github.com/kakoc/birdy/assets/16936618/73ee005d-a877-4980-a549-f1a104b1f816)

As for colors - being able to choose a color for a shape is a more general feature and I'm going to implement it separately in the future.

**Comment by lebe-dev** [comment]
IMO, arrow's body is too thin

**Comment by kakoc** [comment]
> IMO, arrow's body is too thin

Seems like agree with you  
Made all shapes thicker
